version: '3.1'
services:
  stat-server:
    build: stat-service/stat-server
    image: stat-server-image
    container_name: stat-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db-container:5432/stat
      - SPRING_DATASOURCE_USERNAME=admin_stat
      - SPRING_DATASOURCE_PASSWORD=1yWX1bnLDH3leGPOLeJAvLjLPx8ktKH

  stat-db:
    image: postgres:13.7-alpine
    container_name: stat-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=admin_stat
      - POSTGRES_PASSWORD=1yWX1bnLDH3leGPOLeJAvLjLPx8ktKH

  main-service:
    build: main-service
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db-container:5432/main
      - SPRING_DATASOURCE_USERNAME=admin_main
      - SPRING_DATASOURCE_PASSWORD=I0N0UbB0zQL3KUHAgOMsoUdAFGt4pJ1

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=admin_main
      - POSTGRES_PASSWORD=I0N0UbB0zQL3KUHAgOMsoUdAFGt4pJ1