version: '3.1'
services:
  stats-server:
    build: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stat-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stat-db:5432/explore_with_me_statistics
      - DB_NAME=explore_with_me_statistics
      - POSTGRES_USER=admin_explore_with_me
      - POSTGRES_PASSWORD=1Ih5M7EZFxySxivTh0JWPhaFgDTPhOW
      - DB_HOST=db
      - DB_PORT=5432


  stats-db:
    image: postgres:14-alpine
    container_name: stat-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore_with_me_statistics
      - POSTGRES_USER=admin_explore_with_me
      - POSTGRES_PASSWORD=1Ih5M7EZFxySxivTh0JWPhaFgDTPhOW

  ewm-service:
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine